"""Render unresolved wiki evidence as a maintainer review queue."""

from collections import Counter
from urllib.parse import quote


def cell(value):
    return str(value).replace("|", "&#124;").replace("\n", " ")


def page_link(title):
    return f"[{cell(title)}](https://love-live.fandom.com/wiki/{quote(title.replace(' ', '_'), safe='')})"


def source_review(marker, payloads):
    lines = ["# Source enrichment review", "",
             "Generated by scripts/refresh_source.py; edit data/source-overrides.json, then refresh again.",
             "", f"Source snapshot: {marker['snapshotId']}.", "",
             "A missing result means verification failed, not that a recording does not exist. "
             "Wiki performer labels are diagnostic; public credits always come from ll-fans. "
             "All verified vocal alternatives are retained in wiki order and the first is primary; "
             "wikiPage / wikiFile can move an explicit choice first. Use englishName for a verified "
             "performer-name correction; explicit null audio marks a song unavailable.",
             ""]
    for kind, records in zip(("songs", "artists", "series"), payloads):
        evidence = marker["wiki"][kind]
        unresolved = [r for r in records if evidence[r["id"]]["status"] != "verified"]
        counts = Counter(evidence[r["id"]].get("reason", evidence[r["id"]]["status"]) for r in unresolved)
        lines.extend([f"## {kind.title()}: {len(unresolved)} unresolved", "",
                      "; ".join(f"{reason}: {count}" for reason, count in sorted(counts.items())) or "None.", "",
                      "| ID | Name | Status / reason | Page or candidates |",
                      "| --- | --- | --- | --- |"])
        for record in unresolved:
            item = evidence[record["id"]]
            details = []
            if item.get("page"):
                details.append(page_link(item["page"]["title"]))
            details.extend(page_link(c) if kind == "songs" else cell(c) for c in item.get("candidates", []))
            if item.get("artistIds"):
                details.append("Artist IDs: " + ", ".join(item["artistIds"]))
            if item.get("recordings"):
                details.extend(cell(r["title"]) + " (" + ", ".join(r["reasons"]) + ")"
                               for r in item["recordings"])
            reason = item.get("reason", item["status"])
            lines.append(f"| {record['id']} | {cell(record['englishName'])} | "
                         f"{cell(item['status'])}: {cell(reason)} | {'; '.join(details)} |")
        lines.append("")
    return "\n".join(lines)
